version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - node -v
      - npm install
  build:
    commands:
      - echo "VITE_AWS_REGION=${VITE_AWS_REGION}" > .env
      - echo "VITE_AWS_ACCESS_KEY_ID=${VITE_AWS_ACCESS_KEY_ID}" >> .env
      - echo "VITE_AWS_SECRET_ACCESS_KEY=${VITE_AWS_SECRET_ACCESS_KEY}" >> .env
      - echo "VITE_S3_BUCKET_NAME=${VITE_S3_BUCKET_NAME}" >> .env
      - npm run build
  post_build:
    commands:
      - aws s3 sync dist/ s3://${DEST_S3_BUCKET} --delete
